# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('definition', models.TextField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('KZ', 'Kazakh'), ('RU', 'Russian')], max_length=5)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='_word_antonyms_+', to='Dictionary.Word')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='Dictionary.Word')),
                ('translation', models.ManyToManyField(blank=True, related_name='_word_translation_+', to='Dictionary.Word')),
            ],
        ),
    ]
